[[build_tools]]
  name = "cmake"
  version = "3.30.5"
  default = true
  url = "https://github.com/Kitware/CMake/releases/download/v3.30.5/cmake-3.30.5-linux-x86_64.tar.gz"
  sha256 = "f747d9b23e1a252a8beafb4ed2bc2ddf78cff7f04a8e4de19f4ff88e9b51dc9d"
  archive = "cmake-3.30.5-linux-x86_64.tar.gz"
  paths = ["cmake-3.30.5-linux-x86_64/bin"]

[[build_tools]]
  name = "ninja"
  version = "v1.12.1"
  default = true
  url = "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux.zip"
  sha256 = "6f98805688d19672bd699fbbfa2c2cf0fc054ac3df1f0e6a47664d963d530255"
  archive = "ninja-linux-x86_64-v1.12.1.zip"
  paths = ["ninja-linux-x86_64-v1.12.1"]

[[build_tools]]
  name = "ccache"
  version = "4.12.1"
  default = true
  url = "https://github.com/ccache/ccache/releases/download/v4.12.1/ccache-4.12.1-linux-x86_64.tar.xz"
  sha256 = "742e6a6e17c0a060046874eece2949b221c228e1119698a4c6e0b096cbc87152"
  archive = "ccache-4.12.1-linux-x86_64.tar.xz"
  paths = ["ccache-4.12.1-linux-x86_64"]

[[build_tools]]
  name = "llvm"
  version = "17.0.6"
  default = true
  url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.6/clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04.tar.xz"
  sha256 = ""
  archive = "clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04.tar.xz"
  paths = ["clang+llvm-17.0.6-x86_64-linux-gnu-ubuntu-22.04/bin"]

[[build_tools]]
  name = "git-lfs"
  version = "3.5.1"
  default = true
  url = "https://github.com/git-lfs/git-lfs/releases/download/v3.5.1/git-lfs-linux-amd64-v3.5.1.tar.gz"
  sha256 = "6f28eb19faa7a968882dca190d92adc82493378b933958d67ceaeb9ebe4d731e"
  archive = "git-lfs-linux-amd64-v3.5.1.tar.gz"
  paths = ["git-lfs-linux-amd64-v3.5.1/git-lfs-3.5.1"]

[[build_tools]]
  name = "conda"
  version = "26.1.1-3"
  default = true
  url = "https://github.com/conda-forge/miniforge/releases/download/26.1.1-3/Miniforge3-26.1.1-3-Linux-x86_64.sh"
  sha256 = "b25b828b702df4dd2a6d24d4eb56cfa912471dd8e3342cde2c3d86fe3dc2d870"
  archive = "Miniforge3-26.1.1-3-Linux-x86_64.sh"
  paths = ["Miniforge3-26.1.1-3-Linux-x86_64"]
