package configs

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"

	"github.com/celer-pkg/celer/buildtools"
	"github.com/celer-pkg/celer/pkgs/dirs"
	"github.com/celer-pkg/celer/pkgs/expr"
	"github.com/celer-pkg/celer/pkgs/fileio"
)

func (c *Celer) GenerateToolchainFile() error {
	installedDir := fileio.ToRelPath(c.InstalledDir())

	var builder strings.Builder
	builder.WriteString("# ========= WARNING: This toolchain file is generated by celer. ========= #\n")

	fmt.Fprintf(&builder, "\n# Workspace root dir.\n")
	fmt.Fprintf(&builder, `get_filename_component(WORKSPACE_ROOT "${CMAKE_CURRENT_LIST_FILE}" PATH)`+"\n")

	// Make sure installedDir has higher priority than SYSROOT
	c.preExposeInstalledDir(&builder, installedDir)

	// CUDA compiler configuration - MUST be set before toolchain to ensure CMake picks it up during compiler detection.
	c.writeCUDAConfig(&builder)

	// Write toolchain configuration.
	if err := c.platform.Toolchain.generate(&builder); err != nil {
		return err
	}

	// Let execuable binary locate dependency libraries from "../lib" automatically.
	if strings.ToLower(c.platform.Toolchain.GetSystemName()) == "linux" {
		fmt.Fprintf(&builder, "\n# Let executable binary locate dependency libraries from \"../lib\" automatically.\n")
		fmt.Fprintf(&builder, "set(%s %q)\n", "CMAKE_INSTALL_RPATH", `\$ORIGIN/../lib`)
	}

	// Let CMake project generate compile_commands.json.
	fmt.Fprintf(&builder, "\n# Let CMake project generate compile_commands.json.\n")
	fmt.Fprintf(&builder, "set(%s %s)\n", "CMAKE_EXPORT_COMPILE_COMMANDS", "ON")

	// Rootfs related.
	rootfs := c.RootFS()
	if rootfs != nil {
		if err := rootfs.Generate(&builder); err != nil {
			return err
		}
	}

	// Set CMAKE_FIND_ROOT_PATH.
	var rootpaths = []string{"${INSTALLED_DIR}"}
	if c.RootFS() != nil {
		rootpaths = append(rootpaths, "${CMAKE_SYSROOT}")
	}
	fmt.Fprintf(&builder, "\n# Library search root paths.\n")
	fmt.Fprintf(&builder, "if(DEFINED CMAKE_FIND_ROOT_PATH)\n")
	fmt.Fprintf(&builder, `  set(CMAKE_FIND_ROOT_PATH "${CMAKE_FIND_ROOT_PATH}")`+"\n")
	fmt.Fprintf(&builder, "else()\n")
	fmt.Fprintf(&builder, "  set(%s %q)\n", "CMAKE_FIND_ROOT_PATH", strings.Join(rootpaths, ";"))
	fmt.Fprintf(&builder, "endif()\n")

	// Write pkg-config configuration.
	c.writePkgConfig(&builder)

	// Generate Python virtual environment configuration if available.
	if err := c.writePythonVenvConfig(&builder); err != nil {
		return err
	}

	// Set CCache only when enabled.
	if c.configData.CCache != nil {
		if err := c.configData.CCache.Generate(&builder); err != nil {
			return err
		}
	}

	// Define global cmake vars, env vars and macros.
	c.appendVars(&builder)
	c.appendEnvs(&builder)
	c.appendMacros(&builder)

	// Write toolchain file.
	toolchainPath := filepath.Join(dirs.WorkspaceDir, "toolchain_file.cmake")
	if err := os.WriteFile(toolchainPath, []byte(builder.String()), os.ModePerm); err != nil {
		return err
	}

	return nil
}

// preExposeInstalledDir Make sure installedDir has higher priority than SYSROOT
func (c *Celer) preExposeInstalledDir(builder *strings.Builder, installedDir string) {
	installedDevDir := fileio.ToRelPath(c.InstalledDevDir())

	fmt.Fprintf(builder, "\n# Define TMP_DEP_DIR and TMP_DEP_DEV_DIR.\n")
	fmt.Fprintf(builder, "if(DEFINED TMP_DEP_DIR)\n")
	fmt.Fprintf(builder, "  set(INSTALLED_DIR \"${TMP_DEP_DIR}\")\n")
	fmt.Fprintf(builder, "else()\n")
	fmt.Fprintf(builder, "  set(INSTALLED_DIR %q)\n", installedDir)
	fmt.Fprintf(builder, "endif()\n")

	fmt.Fprintf(builder, "\nif(DEFINED TMP_DEP_DEV_DIR)\n")
	fmt.Fprintf(builder, "  set(INSTALLED_DEV_DIR \"${TMP_DEP_DEV_DIR}\")\n")
	fmt.Fprintf(builder, "else()\n")
	fmt.Fprintf(builder, "  set(INSTALLED_DEV_DIR %q)\n", installedDevDir)
	fmt.Fprintf(builder, "endif()\n")

	// Set PATH: add dev bin first.
	fmt.Fprintf(builder, "\n# Dev runtime path.\n")
	fmt.Fprintf(builder, `set(ENV{PATH} "%s%s$ENV{PATH}")`+"\n", "${INSTALLED_DEV_DIR}/bin", string(os.PathListSeparator))

	fmt.Fprintf(builder, "\n# Prefer installed libraries to SYSROOT when present.\n")
	fmt.Fprintf(builder, "list(APPEND CMAKE_PREFIX_PATH %q)\n", "${INSTALLED_DIR}")

	toolchainName := c.platform.Toolchain.GetName()

	// Expose header files.
	fmt.Fprintf(builder, `foreach(flag_var CMAKE_C_FLAGS_INIT CMAKE_CXX_FLAGS_INIT)`+"\n")
	switch runtime.GOOS {
	case "linux":
		if toolchainName == "gcc" || toolchainName == "clang" || toolchainName == "qcc" {
			fmt.Fprintf(builder, `  string(APPEND ${flag_var} " -I${INSTALLED_DIR}/include")`+"\n")
		}
	case "windows":
		if toolchainName == "msvc" || toolchainName == "clang-cl" {
			fmt.Fprintf(builder, `  string(APPEND ${flag_var} "/I ${INSTALLED_DIR}/include")`+"\n")
		}
	case "darwin":
		// TODO: it may supported in the future for darwin.
	}
	fmt.Fprintf(builder, `endforeach()`+"\n\n")

	// Expose library files.
	fmt.Fprintf(builder, `foreach(flag_var CMAKE_SHARED_LINKER_FLAGS_INIT CMAKE_MODULE_LINKER_FLAGS_INIT CMAKE_EXE_LINKER_FLAGS_INIT)`+"\n")
	switch runtime.GOOS {
	case "linux":
		if toolchainName == "gcc" || toolchainName == "clang" || toolchainName == "qcc" {
			fmt.Fprintf(builder, `  string(APPEND ${flag_var} " -L${INSTALLED_DIR}/lib")`+"\n")
			fmt.Fprintf(builder, `  string(APPEND ${flag_var} " -Wl,-rpath-link,${INSTALLED_DIR}/lib")`+"\n")
		}
	case "windows":
		if toolchainName == "msvc" || toolchainName == "clang-cl" {
			fmt.Fprintf(builder, `  string(APPEND ${flag_var} "'/LIBPATH:\"${INSTALLED_DIR}/lib\"'")`+"\n")
		}
	case "darwin":
		// TODO: it may supported in the future for darwin.
	}
	fmt.Fprintf(builder, `endforeach()`+"\n")
}

func (c *Celer) writePkgConfig(toolchain *strings.Builder) {
	var (
		configPaths   []string
		configLibDirs []string
		tmpDepDir     string
		tmpDepSysroot string
	)

	installedDir := filepath.Join("${WORKSPACE_ROOT}/installed", c.LibraryFolder())
	writePathList := func(indent, name string, paths []string) {
		if len(paths) == 0 {
			return
		}

		fmt.Fprintf(toolchain, "%sset(%s\n", indent, name)
		for _, path := range paths {
			fmt.Fprintf(toolchain, "%s  %q\n", indent, path)
		}
		fmt.Fprintf(toolchain, "%s)\n", indent)
		fmt.Fprintf(toolchain, "%slist(JOIN %s %q %s_STR)\n", indent, name, string(os.PathListSeparator), name)
		fmt.Fprintf(toolchain, "%sset(%s %q)\n", indent, "ENV{"+name+"}", "${"+name+"_STR}")
	}

	switch runtime.GOOS {
	case "windows":
		configPaths = []string{
			filepath.ToSlash(filepath.Join(installedDir, "lib", "pkgconfig")),
			filepath.ToSlash(filepath.Join(installedDir, "share", "pkgconfig")),
		}
		tmpDepDir = filepath.ToSlash("${TMP_DEP_DIR}")
		tmpDepSysroot = tmpDepDir

	case "linux":
		tmpDepDir = filepath.ToSlash("${TMP_DEP_DIR}")

		// Target directory.
		if c.RootFS() != nil {
			// tmp/deps is a symlink in rootfs.
			tmpDepSysroot = "${CMAKE_SYSROOT}"

			// Add rootfs pkgconfig paths to both PKG_CONFIG_LIBDIR and PKG_CONFIG_PATH.
			for _, configPath := range c.RootFS().GetPkgConfigPath() {
				configLibDirs = append(configLibDirs, filepath.Join("${CMAKE_SYSROOT}", configPath))
			}
		} else {
			tmpDepSysroot = "${WORKSPACE_ROOT}"
		}
	}

	fmt.Fprintf(toolchain, "\n# ============== PkgConfig search paths ============== #\n")
	fmt.Fprintf(toolchain, "set(PKG_CONFIG_USE_CMAKE_PREFIX_PATH FALSE)\n")
	fmt.Fprintf(toolchain, "set(PKG_CONFIG_EXECUTABLE \"${INSTALLED_DEV_DIR}/bin/pkgconf\")\n")

	// PKG_CONFIG_LIBDIR
	writePathList("", "PKG_CONFIG_LIBDIR", configLibDirs)

	tmpDepConfigPaths := []string{
		filepath.ToSlash(filepath.Join(tmpDepDir, "lib", "pkgconfig")),
		filepath.ToSlash(filepath.Join(tmpDepDir, "share", "pkgconfig")),
	}

	configPaths = []string{
		filepath.ToSlash(filepath.Join("${INSTALLED_DIR}", "lib", "pkgconfig")),
		filepath.ToSlash(filepath.Join("${INSTALLED_DIR}", "share", "pkgconfig")),
	}

	fmt.Fprintf(toolchain, "if(DEFINED TMP_DEP_DIR)\n")
	fmt.Fprintf(toolchain, "  set(ENV{PKG_CONFIG_SYSROOT_DIR} %q)\n", tmpDepSysroot)
	writePathList("  ", "PKG_CONFIG_PATH", tmpDepConfigPaths)
	fmt.Fprintf(toolchain, "else()\n")
	fmt.Fprintf(toolchain, "  set(ENV{PKG_CONFIG_SYSROOT_DIR} \"${WORKSPACE_ROOT}\")\n")
	writePathList("  ", "PKG_CONFIG_PATH", configPaths)
	fmt.Fprintf(toolchain, "endif()\n")
}

// writeCUDAConfig detects CUDA dependencies and writes CUDA compiler configuration to toolchain file.
func (c *Celer) writeCUDAConfig(toolchain *strings.Builder) {
	nvccName := expr.If(runtime.GOOS == "windows", "nvcc.exe", "nvcc")

	// Check if CUDA is required from project configuration.
	containsCUDA := slices.ContainsFunc(c.project.Ports, func(port string) bool {
		return strings.HasPrefix(strings.ToLower(port), "cuda")
	})

	// If not in project config, check if CUDA files exist (backward compatibility).
	if !containsCUDA {
		installedAbsDir := c.InstalledDir()
		nvccAbsPath := filepath.Join(installedAbsDir, "bin", nvccName)
		cudaHeaderAbsPath := filepath.Join(installedAbsDir, "include", "cuda_runtime.h")
		if !fileio.PathExists(nvccAbsPath) || !fileio.PathExists(cudaHeaderAbsPath) {
			return
		}
	}

	// CUDA is available or will be installed, write configuration.
	cudaToolkitRoot := filepath.ToSlash(c.InstalledDir())
	installedRelDir := fileio.ToRelPath(c.InstalledDir())
	nvccCMakePath := filepath.ToSlash(filepath.Join(installedRelDir, "bin", nvccName))

	fmt.Fprintf(toolchain, "\nif(DEFINED TMP_DEP_DIR)\n")
	fmt.Fprintf(toolchain, "  # CUDA compiler configuration.\n")
	fmt.Fprintf(toolchain, `  set(CUDA_TOOLKIT_ROOT_DIR "${TMP_DEP_DIR}" CACHE INTERNAL "CUDA Toolkit root directory.")`+"\n")
	fmt.Fprintf(toolchain, `  set(CUDAToolkit_ROOT "${TMP_DEP_DIR}" CACHE INTERNAL "CUDA Toolkit root directory.")`+"\n")
	fmt.Fprintf(toolchain, `  set(CMAKE_CUDA_COMPILER "${TMP_DEP_DIR}/bin/%s" CACHE INTERNAL "CUDA compiler" FORCE)`+"\n", nvccName)

	if runtime.GOOS == "windows" {
		fmt.Fprintf(toolchain, "\n  # Set CUDA toolset for Visual Studio generator (VS integration is in TMP_DEP_DIR).\n")
		fmt.Fprintf(toolchain, `  set(CMAKE_GENERATOR_TOOLSET "cuda=${TMP_DEP_DIR}" CACHE INTERNAL "CUDA toolset for Visual Studio generator.")`+"\n")
		fmt.Fprintf(toolchain, `  set(CMAKE_VS_PLATFORM_TOOLSET_CUDA "${TMP_DEP_DIR}" CACHE INTERNAL "CUDA toolset path for Visual Studio.")`+"\n")
	}
	fmt.Fprintf(toolchain, "else()\n")
	fmt.Fprintf(toolchain, "  # CUDA compiler configuration.\n")
	fmt.Fprintf(toolchain, "  set(CUDA_TOOLKIT_ROOT_DIR %q CACHE INTERNAL \"CUDA Toolkit root directory.\")\n", cudaToolkitRoot)
	fmt.Fprintf(toolchain, "  set(CUDAToolkit_ROOT %q CACHE INTERNAL \"CUDA Toolkit root directory.\")\n", cudaToolkitRoot)
	fmt.Fprintf(toolchain, "  set(CMAKE_CUDA_COMPILER %q CACHE INTERNAL \"CUDA compiler\" FORCE)\n", nvccCMakePath)

	if runtime.GOOS == "windows" {
		fmt.Fprintf(toolchain, "\n  # Set CUDA toolset for Visual Studio generator.\n")
		fmt.Fprintf(toolchain, "  set(CMAKE_GENERATOR_TOOLSET %q CACHE INTERNAL \"CUDA toolset for Visual Studio generator.\")\n", "cuda="+cudaToolkitRoot)
		fmt.Fprintf(toolchain, "  set(CMAKE_VS_PLATFORM_TOOLSET_CUDA %q CACHE INTERNAL \"CUDA toolset path for Visual Studio.\")\n", cudaToolkitRoot)
	}
	fmt.Fprintf(toolchain, "endif()\n")

	fmt.Fprintf(toolchain, "set(CMAKE_CUDA_FLAGS_INIT %q CACHE STRING \"CUDA compiler flags.\" FORCE)\n",
		"-Wno-deprecated-gpu-targets --forward-unknown-opts --forward-slash-prefix-opts")
}

// writePythonVenvConfig generates Python virtual environment configuration if Python tool is available.
func (c *Celer) writePythonVenvConfig(toolchain *strings.Builder) error {
	// Skip if no Python tool detected.
	if buildtools.PythonTool == nil || buildtools.PythonTool.Path == "" {
		return nil
	}

	// Get python version of current project.
	pythonVersion := buildtools.GetDefaultPythonVersion()
	pythonConfig := c.PythonConfig()
	if pythonConfig != nil && pythonConfig.GetVersion() != "" {
		pythonVersion = pythonConfig.GetVersion()
	}

	// Normalize version to minor version format (e.g., 3.10.5 -> 3.10)
	minorVersion := pythonVersion
	if strings.Count(pythonVersion, ".") > 1 {
		parts := strings.Split(pythonVersion, ".")
		minorVersion = parts[0] + "." + parts[1]
	}

	// Detect Python major version (2 or 3)
	majorVersion := "3"
	if strings.HasPrefix(pythonVersion, "2") {
		majorVersion = "2"
	}

	venvFolder := fmt.Sprintf("venv-%s@%s", minorVersion, c.Project().GetName())
	venvDirAbs := filepath.Join(dirs.WorkspaceDir, "installed", venvFolder)

	// Check if venv directory exists
	if !fileio.PathExists(venvDirAbs) {
		return nil
	}

	venvDir := filepath.Join("${WORKSPACE_ROOT}", "installed", venvFolder)

	// Write Python virtual environment configuration
	fmt.Fprintf(toolchain, "\n# ============== Python %s virtual environment ============== #\n", majorVersion)
	fmt.Fprintf(toolchain, "# Python venv location.\n")
	fmt.Fprintf(toolchain, "set(PYTHON_VENV_DIR %q)\n\n", venvDir)

	if majorVersion == "3" {
		// Python3 configuration using modern Find(Python3)
		fmt.Fprintf(toolchain, "# Python3 executable and libraries\n")
		fmt.Fprintf(toolchain, "set(Python3_EXECUTABLE \"${PYTHON_VENV_DIR}/bin/python3\" CACHE FILEPATH \"Python3 executable\")\n")
		fmt.Fprintf(toolchain, "set(Python3_INCLUDE_DIR \"${PYTHON_VENV_DIR}/include\" CACHE PATH \"Python3 include directory\")\n")
		fmt.Fprintf(toolchain, "set(Python3_LIBRARY_DIR \"${PYTHON_VENV_DIR}/lib\" CACHE PATH \"Python3 library directory\")\n")
		fmt.Fprintf(toolchain, "set(Python3_ROOT_DIR \"${PYTHON_VENV_DIR}\" CACHE PATH \"Python3 root directory\")\n")
		fmt.Fprintf(toolchain, "\n# For CMake find_package(Python3) to correctly locate the venv Python.\n")
		fmt.Fprintf(toolchain, "list(APPEND CMAKE_PREFIX_PATH \"${PYTHON_VENV_DIR}\")\n")
	} else {
		// Python2 configuration using legacy Find(PythonLibs)
		fmt.Fprintf(toolchain, "# Python2 executable and libraries\n")
		fmt.Fprintf(toolchain, "set(PYTHON_EXECUTABLE \"${PYTHON_VENV_DIR}/bin/python\" CACHE FILEPATH \"Python executable\")\n")
		fmt.Fprintf(toolchain, "set(PYTHON_INCLUDE_DIR \"${PYTHON_VENV_DIR}/include/python%s\" CACHE PATH \"Python include directory\")\n", minorVersion)
		fmt.Fprintf(toolchain, "set(PYTHON_LIBRARY_DIR \"${PYTHON_VENV_DIR}/lib\" CACHE PATH \"Python library directory\")\n")
		fmt.Fprintf(toolchain, "\n# For CMake find_package(PythonLibs) to correctly locate the venv Python2.\n")
		fmt.Fprintf(toolchain, "set(PYTHONLIBS_FOUND TRUE CACHE BOOL \"Python libraries found\")\n")
		fmt.Fprintf(toolchain, "list(APPEND CMAKE_PREFIX_PATH \"${PYTHON_VENV_DIR}\")\n")
	}

	fmt.Fprintf(toolchain, "\n# Set environment variables for Python package discovery.\n")
	siteRel := fmt.Sprintf("lib/python%s/site-packages", minorVersion)
	sep := string(os.PathListSeparator)
	fmt.Fprintf(toolchain, "set(ENV{PYTHONPATH} \"${INSTALLED_DIR}/%s%s${PYTHON_VENV_DIR}/%s%s$ENV{PYTHONPATH}\")\n\n", siteRel, sep, siteRel, sep)

	if runtime.GOOS != "windows" {
		fmt.Fprintf(toolchain, "# Add venv bin to PATH so tools are accessible.\n")
		fmt.Fprintf(toolchain, "set(ENV{PATH} \"${PYTHON_VENV_DIR}/bin%s$ENV{PATH}\")\n", string(os.PathListSeparator))
	}

	// Add LD_LIBRARY_PATH for conda-based Python on Linux/macOS to find libpython and other dependencies
	if buildtools.PythonTool != nil && buildtools.PythonTool.LdLibraryPath() != "" && runtime.GOOS != "windows" {
		fmt.Fprintf(toolchain, "\n# Add conda lib directory to LD_LIBRARY_PATH for libpython and other shared libraries.\n")
		fmt.Fprintf(toolchain, "set(ENV{LD_LIBRARY_PATH} \"%s%s$ENV{LD_LIBRARY_PATH}\")\n",
			buildtools.PythonTool.LdLibraryPath(), string(os.PathListSeparator))
	}

	return nil
}

func (c *Celer) appendVars(toolchain *strings.Builder) {
	for index, item := range c.project.Vars {
		if index == 0 {
			fmt.Fprintf(toolchain, "\n# =============== Global CMake variables =============== #\n")
		}

		parts := strings.Split(item, "=")

		// Define cmake var in project will make package cache not inaccurate.
		if strings.HasPrefix(strings.ToLower(parts[0]), "cmake_") {
			panic(fmt.Sprintf("%q as cmake var should not be defined in project %q", item, c.project.Name))
		}

		// cmake var should be like 'aa=bb' or 'aa'
		if len(parts) != 1 && len(parts) != 2 {
			panic("invalid cmake var: " + item)
		}

		if len(parts) == 1 {
			fmt.Fprintf(toolchain, `set(%s CACHE INTERNAL "")`+"\n", item)
		} else if len(parts) == 2 {
			parts[1] = c.exprVars.Expand(parts[1])
			fmt.Fprintf(toolchain, `set(%s %s CACHE INTERNAL "")`+"\n", parts[0], parts[1])
		}
	}
}

func (c *Celer) appendEnvs(toolchain *strings.Builder) {
	for index, item := range c.project.Envs {
		parts := strings.Split(item, "=")
		if len(parts) != 2 {
			panic("invalid env var: " + item)
		}

		if index == 0 {
			fmt.Fprintf(toolchain, "\n# =============== Global environment variables =============== #\n")
		}

		parts[1] = c.exprVars.Expand(parts[1])
		fmt.Fprintf(toolchain, `set(ENV{%s} "%s%s$ENV{%s}")`+"\n", parts[0], parts[1], string(os.PathListSeparator), parts[0])
	}
}

func (c *Celer) appendMacros(toolchain *strings.Builder) {
	for index, item := range c.project.Macros {
		if index == 0 {
			fmt.Fprintf(toolchain, "\n# =============== Global C/C++ Macros =============== #\n")
		}

		item = c.exprVars.Expand(item)
		fmt.Fprintf(toolchain, "add_compile_definitions(%s)\n", item)
	}
}
