package configs

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"

	"github.com/celer-pkg/celer/buildtools"
	"github.com/celer-pkg/celer/pkgs/dirs"
	"github.com/celer-pkg/celer/pkgs/expr"
	"github.com/celer-pkg/celer/pkgs/fileio"
)

func (c *Celer) GenerateToolchainFile() error {
	var toolchain strings.Builder
	toolchain.WriteString("# ========= WARNING: This toolchain file is generated by celer. ========= #\n")

	fmt.Fprintf(&toolchain, "\n# Workspace root dir.\n")
	fmt.Fprintf(&toolchain, `get_filename_component(WORKSPACE_ROOT "${CMAKE_CURRENT_LIST_FILE}" PATH)`+"\n")

	// Set CMAKE_PREFIX_PATH before setting CMAKE_SYSROOT to locate libraries of dependencies FIRST (before sysroot)
	installedDir := fileio.ToRelPath(c.InstalledDir())
	fmt.Fprintf(&toolchain, "\n# Dependency search paths.\n")
	fmt.Fprintf(&toolchain, "list(APPEND CMAKE_PREFIX_PATH %q)\n", installedDir)

	// Set PATH: add dev bin first.
	installedDevDir := fileio.ToRelPath(c.InstalledDevDir())
	fmt.Fprintf(&toolchain, `set(ENV{PATH} "%s%s$ENV{PATH}")`+"\n", installedDevDir+"/bin", string(os.PathListSeparator))

	// CUDA compiler configuration - MUST be set before toolchain to ensure CMake picks it up during compiler detection.
	c.writeCUDAConfig(&toolchain)

	// Toolchain related.
	if err := c.platform.Toolchain.generate(&toolchain); err != nil {
		return err
	}

	// Rootfs related.
	rootfs := c.RootFS()
	if rootfs != nil {
		if err := rootfs.Generate(&toolchain); err != nil {
			return err
		}
	}

	// Write pkg-config configuration.
	c.writePkgConfig(&toolchain)

	// Generate Python virtual environment configuration if available.
	if err := c.writePythonVenvConfig(&toolchain); err != nil {
		return err
	}

	// Set CMAKE_FIND_ROOT_PATH.
	var rootpaths = []string{installedDir}
	if c.RootFS() != nil {
		rootpaths = append(rootpaths, "${CMAKE_SYSROOT}")
	}
	fmt.Fprintf(&toolchain, "\n# Package search root paths.\n")
	fmt.Fprintf(&toolchain, "if(DEFINED CMAKE_FIND_ROOT_PATH)\n")
	fmt.Fprintf(&toolchain, `  set(CMAKE_FIND_ROOT_PATH "${CMAKE_FIND_ROOT_PATH}")`+"\n")
	fmt.Fprintf(&toolchain, "else()\n")
	fmt.Fprintf(&toolchain, "  set(%s %q)\n", "CMAKE_FIND_ROOT_PATH", strings.Join(rootpaths, ";"))
	fmt.Fprintf(&toolchain, "endif()\n")

	// Set CCache only when enabled.
	if c.configData.CCache != nil {
		if err := c.configData.CCache.Generate(&toolchain); err != nil {
			return err
		}
	}

	// Define global cmake vars, env vars and macros.
	c.appendIncludeDirs(&toolchain)
	c.appendLibDirs(&toolchain)
	c.appendVars(&toolchain)
	c.appendEnvs(&toolchain)
	c.appendMacros(&toolchain)

	fmt.Fprintf(&toolchain, "\n")
	if strings.ToLower(c.platform.Toolchain.GetSystemName()) == "linux" {
		fmt.Fprintf(&toolchain, "set(%s %q)\n", "CMAKE_INSTALL_RPATH", `\$ORIGIN/../lib`)
	}
	fmt.Fprintf(&toolchain, "set(%s %s)\n", "CMAKE_EXPORT_COMPILE_COMMANDS", "ON")

	// Write toolchain file.
	toolchainPath := filepath.Join(dirs.WorkspaceDir, "toolchain_file.cmake")
	if err := os.WriteFile(toolchainPath, []byte(toolchain.String()), os.ModePerm); err != nil {
		return err
	}

	return nil
}

func (c *Celer) writePkgConfig(toolchain *strings.Builder) {
	var (
		configPaths   []string
		configLibDirs []string
		sysrootDir    string
		tmpDepDir     string
		tmpDepSysroot string
	)

	libraryFolder := filepath.Join(c.Platform().GetName(), c.Project().GetName(), c.BuildType())
	installedDir := filepath.Join("${WORKSPACE_ROOT}/installed", libraryFolder)
	writePathList := func(indent, name string, paths []string) {
		if len(paths) == 0 {
			return
		}

		toolchain.WriteString(indent + "set(" + name + "\n")
		for _, path := range paths {
			toolchain.WriteString(fmt.Sprintf("%s  %q", indent, path) + "\n")
		}
		toolchain.WriteString(indent + ")\n")
		toolchain.WriteString(fmt.Sprintf(`%slist(JOIN %s "%s" %s_STR)`, indent, name, string(os.PathListSeparator), name) + "\n")
		fmt.Fprintf(toolchain, "%sset(%s %q)\n", indent, "ENV{"+name+"}", "${"+name+"_STR}")
	}

	switch runtime.GOOS {
	case "windows":
		configPaths = []string{
			filepath.ToSlash(filepath.Join(installedDir, "lib", "pkgconfig")),
			filepath.ToSlash(filepath.Join(installedDir, "share", "pkgconfig")),
		}
		sysrootDir = filepath.ToSlash(installedDir)
		tmpDepDir = filepath.ToSlash("${TMP_DEP_DIR}")
		tmpDepSysroot = tmpDepDir

	case "linux":
		tmpDepDir = filepath.ToSlash("${TMP_DEP_DIR}")

		// Target directory.
		var targetDir string
		if c.RootFS() != nil {
			// tmp/deps is a symlink in rootfs.
			sysrootDir = "${CMAKE_SYSROOT}"
			tmpDepSysroot = "${CMAKE_SYSROOT}"
			targetDir = filepath.Join(sysrootDir, "tmp", "deps", libraryFolder)

			// Prepend pkgconfig with tmp/deps directory to prioritize it.
			configPaths = []string{
				filepath.Join(targetDir, "lib", "pkgconfig"),
				filepath.Join(targetDir, "share", "pkgconfig"),
			}

			// Add rootfs pkgconfig paths to both PKG_CONFIG_LIBDIR and PKG_CONFIG_PATH.
			for _, configPath := range c.RootFS().GetPkgConfigPath() {
				configLibDirs = append(configLibDirs, filepath.Join("${CMAKE_SYSROOT}", configPath))
			}
		} else {
			sysrootDir = "${WORKSPACE_ROOT}/installed"
			tmpDepSysroot = "${WORKSPACE_ROOT}"
			targetDir = sysrootDir

			// Fallback pkgconfig paths when building outside the celer build pipeline.
			configPaths = []string{
				filepath.Join(targetDir, "lib", "pkgconfig"),
				filepath.Join(targetDir, "share", "pkgconfig"),
			}
		}
	}

	fmt.Fprintf(toolchain, "\n# ============== pkg-config search paths ============== #\n")
	executablePath := fmt.Sprintf("${WORKSPACE_ROOT}/installed/%s-dev/bin/pkgconf", c.platform.GetHostName())
	fmt.Fprintf(toolchain, "set(PKG_CONFIG_USE_CMAKE_PREFIX_PATH FALSE)\n")
	fmt.Fprintf(toolchain, "set(PKG_CONFIG_EXECUTABLE %q)\n", executablePath)

	// PKG_CONFIG_LIBDIR
	writePathList("", "PKG_CONFIG_LIBDIR", configLibDirs)

	tmpDepConfigPaths := []string{
		filepath.ToSlash(filepath.Join(tmpDepDir, "lib", "pkgconfig")),
		filepath.ToSlash(filepath.Join(tmpDepDir, "share", "pkgconfig")),
	}

	fmt.Fprintf(toolchain, "if(DEFINED TMP_DEP_DIR)\n")
	fmt.Fprintf(toolchain, "  set(ENV{PKG_CONFIG_SYSROOT_DIR} %q)\n", tmpDepSysroot)
	writePathList("  ", "PKG_CONFIG_PATH", tmpDepConfigPaths)
	fmt.Fprintf(toolchain, "else()\n")
	fmt.Fprintf(toolchain, "  set(ENV{PKG_CONFIG_SYSROOT_DIR} %q)\n", sysrootDir)
	writePathList("  ", "PKG_CONFIG_PATH", configPaths)
	fmt.Fprintf(toolchain, "endif()\n")
}

// writeCUDAConfig detects CUDA dependencies and writes CUDA compiler configuration to toolchain file.
func (c *Celer) writeCUDAConfig(toolchain *strings.Builder) {
	nvccName := expr.If(runtime.GOOS == "windows", "nvcc.exe", "nvcc")

	// Check if CUDA is required from project configuration.
	containsCUDA := slices.ContainsFunc(c.project.Ports, func(port string) bool {
		return strings.HasPrefix(strings.ToLower(port), "cuda")
	})

	// If not in project config, check if CUDA files exist (backward compatibility).
	if !containsCUDA {
		installedAbsDir := c.InstalledDir()
		nvccAbsPath := filepath.Join(installedAbsDir, "bin", nvccName)
		cudaHeaderAbsPath := filepath.Join(installedAbsDir, "include", "cuda_runtime.h")
		if !fileio.PathExists(nvccAbsPath) || !fileio.PathExists(cudaHeaderAbsPath) {
			return
		}
	}

	// CUDA is available or will be installed, write configuration.
	cudaToolkitRoot := filepath.ToSlash(c.InstalledDir())
	installedRelDir := fileio.ToRelPath(c.InstalledDir())
	nvccCMakePath := filepath.ToSlash(filepath.Join(installedRelDir, "bin", nvccName))

	fmt.Fprintf(toolchain, "\nif(DEFINED TMP_DEP_DIR)\n")
	fmt.Fprintf(toolchain, "  # CUDA compiler configuration.\n")
	fmt.Fprintf(toolchain, `  set(CUDA_TOOLKIT_ROOT_DIR "${TMP_DEP_DIR}" CACHE INTERNAL "CUDA Toolkit root directory.")`+"\n")
	fmt.Fprintf(toolchain, `  set(CUDAToolkit_ROOT "${TMP_DEP_DIR}" CACHE INTERNAL "CUDA Toolkit root directory.")`+"\n")
	fmt.Fprintf(toolchain, `  set(CMAKE_CUDA_COMPILER "${TMP_DEP_DIR}/bin/%s" CACHE INTERNAL "CUDA compiler" FORCE)`+"\n", nvccName)

	if runtime.GOOS == "windows" {
		fmt.Fprintf(toolchain, "\n  # Set CUDA toolset for Visual Studio generator (VS integration is in TMP_DEP_DIR).\n")
		fmt.Fprintf(toolchain, `  set(CMAKE_GENERATOR_TOOLSET "cuda=${TMP_DEP_DIR}" CACHE INTERNAL "CUDA toolset for Visual Studio generator.")`+"\n")
		fmt.Fprintf(toolchain, `  set(CMAKE_VS_PLATFORM_TOOLSET_CUDA "${TMP_DEP_DIR}" CACHE INTERNAL "CUDA toolset path for Visual Studio.")`+"\n")
	}
	fmt.Fprintf(toolchain, "else()\n")
	fmt.Fprintf(toolchain, "  # CUDA compiler configuration.\n")
	fmt.Fprintf(toolchain, "  set(CUDA_TOOLKIT_ROOT_DIR %q CACHE INTERNAL \"CUDA Toolkit root directory.\")\n", cudaToolkitRoot)
	fmt.Fprintf(toolchain, "  set(CUDAToolkit_ROOT %q CACHE INTERNAL \"CUDA Toolkit root directory.\")\n", cudaToolkitRoot)
	fmt.Fprintf(toolchain, "  set(CMAKE_CUDA_COMPILER %q CACHE INTERNAL \"CUDA compiler\" FORCE)\n", nvccCMakePath)

	if runtime.GOOS == "windows" {
		fmt.Fprintf(toolchain, "\n  # Set CUDA toolset for Visual Studio generator.\n")
		fmt.Fprintf(toolchain, "  set(CMAKE_GENERATOR_TOOLSET %q CACHE INTERNAL \"CUDA toolset for Visual Studio generator.\")\n", "cuda="+cudaToolkitRoot)
		fmt.Fprintf(toolchain, "  set(CMAKE_VS_PLATFORM_TOOLSET_CUDA %q CACHE INTERNAL \"CUDA toolset path for Visual Studio.\")\n", cudaToolkitRoot)
	}
	fmt.Fprintf(toolchain, "endif()\n")

	fmt.Fprintf(toolchain, "set(CMAKE_CUDA_FLAGS_INIT %q CACHE STRING \"CUDA compiler flags.\" FORCE)\n",
		"-Wno-deprecated-gpu-targets --forward-unknown-opts --forward-slash-prefix-opts")
}

// writePythonVenvConfig generates Python virtual environment configuration if Python tool is available.
func (c *Celer) writePythonVenvConfig(toolchain *strings.Builder) error {
	// Skip if no Python tool detected.
	if buildtools.PythonTool == nil || buildtools.PythonTool.Path == "" {
		return nil
	}

	// Get python version of current project.
	pythonVersion := buildtools.GetDefaultPythonVersion()
	pythonConfig := c.PythonConfig()
	if pythonConfig != nil && pythonConfig.GetVersion() != "" {
		pythonVersion = pythonConfig.GetVersion()
	}

	// Normalize version to minor version format (e.g., 3.10.5 -> 3.10)
	minorVersion := pythonVersion
	if strings.Count(pythonVersion, ".") > 1 {
		parts := strings.Split(pythonVersion, ".")
		minorVersion = parts[0] + "." + parts[1]
	}

	// Detect Python major version (2 or 3)
	majorVersion := "3"
	if strings.HasPrefix(pythonVersion, "2") {
		majorVersion = "2"
	}

	venvFolder := fmt.Sprintf("venv-%s@%s", minorVersion, c.Project().GetName())
	venvDirAbs := filepath.Join(dirs.WorkspaceDir, "installed", venvFolder)

	// Check if venv directory exists
	if !fileio.PathExists(venvDirAbs) {
		return nil
	}

	venvDir := filepath.Join("${WORKSPACE_ROOT}", "installed", venvFolder)

	// Write Python virtual environment configuration
	fmt.Fprintf(toolchain, "\n# ============== Python %s virtual environment ============== #\n", majorVersion)
	fmt.Fprintf(toolchain, "# Python venv location.\n")
	fmt.Fprintf(toolchain, "set(PYTHON_VENV_DIR %q)\n", venvDir)
	fmt.Fprintf(toolchain, "\n")

	if majorVersion == "3" {
		// Python3 configuration using modern Find(Python3)
		fmt.Fprintf(toolchain, "# Python3 executable and libraries\n")
		fmt.Fprintf(toolchain, "set(Python3_EXECUTABLE \"${PYTHON_VENV_DIR}/bin/python3\" CACHE FILEPATH \"Python3 executable\")\n")
		fmt.Fprintf(toolchain, "set(Python3_INCLUDE_DIR \"${PYTHON_VENV_DIR}/include\" CACHE PATH \"Python3 include directory\")\n")
		fmt.Fprintf(toolchain, "set(Python3_LIBRARY_DIR \"${PYTHON_VENV_DIR}/lib\" CACHE PATH \"Python3 library directory\")\n")
		fmt.Fprintf(toolchain, "set(Python3_ROOT_DIR \"${PYTHON_VENV_DIR}\" CACHE PATH \"Python3 root directory\")\n")
		fmt.Fprintf(toolchain, "\n")
		fmt.Fprintf(toolchain, "# For CMake find_package(Python3) to correctly locate the venv Python.\n")
		fmt.Fprintf(toolchain, "list(APPEND CMAKE_PREFIX_PATH \"${PYTHON_VENV_DIR}\")\n")
	} else {
		// Python2 configuration using legacy Find(PythonLibs)
		fmt.Fprintf(toolchain, "# Python2 executable and libraries\n")
		fmt.Fprintf(toolchain, "set(PYTHON_EXECUTABLE \"${PYTHON_VENV_DIR}/bin/python\" CACHE FILEPATH \"Python executable\")\n")
		fmt.Fprintf(toolchain, "set(PYTHON_INCLUDE_DIR \"${PYTHON_VENV_DIR}/include/python%s\" CACHE PATH \"Python include directory\")\n", minorVersion)
		fmt.Fprintf(toolchain, "set(PYTHON_LIBRARY_DIR \"${PYTHON_VENV_DIR}/lib\" CACHE PATH \"Python library directory\")\n")
		fmt.Fprintf(toolchain, "\n")
		fmt.Fprintf(toolchain, "# For CMake find_package(PythonLibs) to correctly locate the venv Python2.\n")
		fmt.Fprintf(toolchain, "set(PYTHONLIBS_FOUND TRUE CACHE BOOL \"Python libraries found\")\n")
		fmt.Fprintf(toolchain, "list(APPEND CMAKE_PREFIX_PATH \"${PYTHON_VENV_DIR}\")\n")
	}

	fmt.Fprintf(toolchain, "\n")
	fmt.Fprintf(toolchain, "# Set environment variables for Python package discovery.\n")
	fmt.Fprintf(toolchain, "set(ENV{PYTHONPATH} \"${PYTHON_VENV_DIR}/lib/python%s/site-packages:$ENV{PYTHONPATH}\")\n", minorVersion)
	fmt.Fprintf(toolchain, "\n")

	fmt.Fprintf(toolchain, "# Add venv bin to PATH so tools like imoapp, zosidl, etc. are accessible.\n")
	fmt.Fprintf(toolchain, "set(ENV{PATH} \"${PYTHON_VENV_DIR}/bin:$ENV{PATH}\")\n")

	// Add LD_LIBRARY_PATH for conda-based Python on Linux/macOS to find libpython and other dependencies
	if buildtools.PythonTool != nil && buildtools.PythonTool.LdLibraryPath() != "" && runtime.GOOS != "windows" {
		fmt.Fprintf(toolchain, "\n")
		fmt.Fprintf(toolchain, "# Add conda lib directory to LD_LIBRARY_PATH for libpython and other shared libraries.\n")
		fmt.Fprintf(toolchain, "set(ENV{LD_LIBRARY_PATH} \"%s:$ENV{LD_LIBRARY_PATH}\")\n", buildtools.PythonTool.LdLibraryPath())
	}

	return nil
}

func (c *Celer) appendIncludeDirs(toolchain *strings.Builder) {
	for index, dir := range c.project.IncludeDirs {
		if index == 0 {
			fmt.Fprintf(toolchain, "\n# =============== External include directories =============== #\n")
		}

		// Also add include path to compiler flags to ensure headers are found
		// This is necessary because CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY may restrict include_directories()
		dir = c.exprVars.Expand(dir)
		escapedDir := filepath.ToSlash(dir)
		systemName := c.platform.Toolchain.GetSystemName()

		if strings.ToLower(systemName) == "windows" &&
			(c.platform.Toolchain.GetName() == "msvc" ||
				c.platform.Toolchain.GetName() == "clang-cl") {
			// Windows MSVC: use /I format
			fmt.Fprintf(toolchain, `foreach(flag_var CMAKE_C_FLAGS_INIT CMAKE_CXX_FLAGS_INIT)`+"\n")
			fmt.Fprintf(toolchain, `  string(APPEND ${flag_var} " /I\"%s\"")`+"\n", escapedDir)
			fmt.Fprintf(toolchain, `endforeach()`+"\n")
		} else {
			// Unix/Linux: use -I format
			fmt.Fprintf(toolchain, `foreach(flag_var CMAKE_C_FLAGS_INIT CMAKE_CXX_FLAGS_INIT)`+"\n")
			fmt.Fprintf(toolchain, `  string(APPEND ${flag_var} " -I%s")`+"\n", escapedDir)
			fmt.Fprintf(toolchain, `endforeach()`+"\n")
		}
	}
}

func (c *Celer) appendLibDirs(toolchain *strings.Builder) {
	for index, dir := range c.project.LibDirs {
		if index == 0 {
			fmt.Fprintf(toolchain, "\n# =============== External library directories =============== # \n")
		}

		// Add library path to linker flags to ensure libraries are found,
		// This is necessary because CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY may restrict link_directories()
		dir = c.exprVars.Expand(dir)
		escapedDir := filepath.ToSlash(dir)
		systemName := c.platform.Toolchain.GetSystemName()

		if strings.ToLower(systemName) == "windows" &&
			(c.platform.Toolchain.GetName() == "msvc" ||
				c.platform.Toolchain.GetName() == "clang-cl") {
			// Windows MSVC: use /LIBPATH: format
			fmt.Fprintf(toolchain, `foreach(flag_var CMAKE_SHARED_LINKER_FLAGS_INIT CMAKE_MODULE_LINKER_FLAGS_INIT CMAKE_EXE_LINKER_FLAGS_INIT)`+"\n")
			fmt.Fprintf(toolchain, `  string(APPEND ${flag_var} " /LIBPATH:\"%s\"")`+"\n", escapedDir)
			fmt.Fprintf(toolchain, `endforeach()`+"\n")
		} else {
			// Unix/Linux: use -L format
			fmt.Fprintf(toolchain, `foreach(flag_var CMAKE_SHARED_LINKER_FLAGS_INIT CMAKE_MODULE_LINKER_FLAGS_INIT CMAKE_EXE_LINKER_FLAGS_INIT)`+"\n")
			fmt.Fprintf(toolchain, `  string(APPEND ${flag_var} " -L%s")`+"\n", escapedDir)
			fmt.Fprintf(toolchain, `  string(APPEND ${flag_var} " -Wl,-rpath-link,%s")`+"\n", escapedDir)
			fmt.Fprintf(toolchain, `endforeach()`+"\n")
		}
	}
}

func (c *Celer) appendVars(toolchain *strings.Builder) {
	for index, item := range c.project.Vars {
		if index == 0 {
			fmt.Fprintf(toolchain, "\n# =============== Global CMake variables =============== #\n")
		}

		parts := strings.Split(item, "=")

		// Define cmake var in project will make package cache not inaccurate.
		if strings.HasPrefix(strings.ToLower(parts[0]), "cmake_") {
			panic(fmt.Sprintf("%q as cmake var should not be defined in project %q", item, c.project.Name))
		}

		// cmake var should be like 'aa=bb' or 'aa'
		if len(parts) != 1 && len(parts) != 2 {
			panic("invalid cmake var: " + item)
		}

		if len(parts) == 1 {
			fmt.Fprintf(toolchain, `set(%s CACHE INTERNAL "global value")`+"\n", item)
		} else if len(parts) == 2 {
			parts[1] = c.exprVars.Expand(parts[1])
			fmt.Fprintf(toolchain, `set(%s %s CACHE INTERNAL "global value")`+"\n", parts[0], parts[1])
		}
	}
}

func (c *Celer) appendEnvs(toolchain *strings.Builder) {
	for index, item := range c.project.Envs {
		parts := strings.Split(item, "=")
		if len(parts) != 2 {
			panic("invalid env var: " + item)
		}

		if index == 0 {
			fmt.Fprintf(toolchain, "\n# =============== Global environment variables =============== #s\n")
		}

		parts[1] = c.exprVars.Expand(parts[1])
		fmt.Fprintf(toolchain, `set(ENV{%s} "%s")`+"\n", parts[0], parts[1])
	}
}

func (c *Celer) appendMacros(toolchain *strings.Builder) {
	for index, item := range c.project.Macros {
		if index == 0 {
			fmt.Fprintf(toolchain, "\n# =============== Global C/C++ Macros =============== #\n")
		}

		item = c.exprVars.Expand(item)
		fmt.Fprintf(toolchain, "add_compile_definitions(%s)\n", item)
	}
}
